config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'sample/index'
  get 'header/edit'
  get 'default_site', to: 'home#change_site'
  resources 'cms', controller: :home do
    resources :header, only: [:edit, :update]
    resources :widget, only: [:show, :edit, :update]
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::ActiveStorage

  attr_accessor :data

  has_one_attached :storage_data
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_content
    rails_representation_url(storage_data.variant(resize: '800>').processed, only_path: true)
  end

  def url_thumb
    rails_representation_url(storage_data.variant(resize: '118x100').processed, only_path: true)
  end
end

app/models/header.rb
class Header < ApplicationRecord
    has_one_attached :logo
    has_many :menus, dependent: :destroy
    accepts_nested_attributes_for :menus, allow_destroy: true, reject_if: proc { |att| att['name'].blank? }
    has_one :widget
    has_one :theme
end

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :header, optional: true
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :theme
    belongs_to :widget
end

app/models/theme.rb
class Theme < ApplicationRecord
    belongs_to :header  
    has_many :themes
end

app/models/widget.rb
class Widget < ApplicationRecord
  belongs_to :header
  has_many :sections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :widget

    private
    def widget
        puts "<<<<<<<<<<<<<<<< Test <<<<<<<<<<<<<<"
        if (@widget = Widget.find_by_published(true))
            puts "@widget <<<<<<<<<<<<<<< #{@widget}"
            # @widget = nil
            @header = Header.find(@widget.header_id)
            @menus = @header.menus
            @logo = @header.logo
        end
    end
end

app/controllers/header_controller.rb
class HeaderController < ApplicationController
  def edit
    @cms = Theme.find(params[:cm_id])
    @header = Header.find(params[:id])
    @header.menus.build
  end

  def update
    puts "params <<<<<<< #{params}"
    @header = Header.find(params[:id])
    @cms = Theme.find(params[:cm_id])
    @widget = Theme.find(params[:cm_id])
    if @header.update_attributes(set_header_params)
      redirect_to cm_widget_path(@cms, @widget)
    else
      render :edit
    end
  end

  private
  def set_header_params
    params.require(:header).permit(:logo, menus_attributes: Menu.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])
    @header = Header.find(@theme.header_id)
    @menus = @header.menus
    @logo = @header.logo
  end

  def change_site
    Widget.all.each do |w|
      w.published = false
      w.save
    end
    redirect_to spree_path
  end
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def index
  end
end

app/controllers/widget_controller.rb
class WidgetController < ApplicationController
  def show
    @widget = Widget.find(params[:id])
    @cms = Theme.find(params[:id])
    @header = Header.find(@widget.header_id)
    @menus = @header.menus
    @logo = @header.logo
  end

  def update
    puts "params <<<<<< #{params}"
    Widget.all.each do |w|
      if w.id == params[:id].to_i
        w.published = true
      else
        w.published = false
      end
      w.save
    end
    redirect_to spree_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(themeid)
    if themeid == 2
      "<header class='main_menu home_menu'><div class='container-fluid'><div class='row align-items-center justify-content-center'><div class='col-lg-11'><nav class='navbar navbar-expand-lg navbar-light'><a class='navbar-brand' href='index.html'><img src='/assets/winter_img/logo.png'/></a><button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'></button><div class='collapse navbar-collapse main-menu-item' id='navbarSupportedContent'><ul class='navbar-nav'>" + "#{@menus.map { |menu| menu['field_type'] == 'text' ? "<li class='nav-item'><a class='nav-link' href=#{menu['redirect_url']}>#{menu['label']}</a></li>" : "<li class='nav-item dropdown'><a class='nav-link dropdown-toggle' href='blog.html' id='navbarDropdown_1' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>#{menu['label']}</a><div class='dropdown-menu' aria-labelledby='navbarDropdown_1'>" + "#{menu.values.split(";").map { |value| "<a class='dropdown-item' href=#{value.split(',').last}>#{value.split(',').first}</a>" }.join('')}" + '</div></li>'}.join('')}" + "</ul></div></nav></div></div></div></header>"
    elsif themeid == 3
      "<nav class='navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light' id='ftco-navbar'><div class='container'><a class='navbar-brand' href='index.html'><img src='/assets/winter_img/logo.png'/></a><div class='collapse navbar-collapse' id='ftco-nav'><ul class='navbar-nav ml-auto'>" + "#{@menus.map { |menu| menu['field_type'] == 'text' ? "<li class='nav-item active'><a class='nav-link' href=#{menu['redirect_url']}>#{menu['label']}</a></li>" : "<li class='nav-item dropdown'><a class='nav-link dropdown-toggle' href='blog.html' id='dropdown04' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>#{menu['label']}</a><div class='dropdown-menu' aria-labelledby='dropdown04'>" + "#{menu.values.split(";").map { |value| "<a class='dropdown-item' href=#{value.split(',').last}>#{value.split(',').first}</a>" }.join('')}" + '</div></li>'}.join('')}" + "</ul></div></div></nav>"
    else
      "<header class='header-section'><nav class='main-navbar'><div class='container'><a class='navbar-brand' href='index.html'><img src='/assets/winter_img/logo.png'/><ul class='main-menu'>" + "#{@menus.map { |menu| menu['field_type'] == 'text' ? "<li><a href=#{menu['redirect_url']}>#{menu['label']}</a></li>" : "<li><a href='index.html'>#{menu['label']}</a><ul class='sub-menu'>" + "#{menu.values.split(";").map { |value| "<li><a href=#{value.split(',').last}>#{value.split(',').first}</a></li>" }.join('')}" + '</ul></li>'}.join('')}" + "</div></nav></header>"
    end 
  end

  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields " + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/header_helper.rb
module HeaderHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/widget_helper.rb
module WidgetHelper
end

app/views/home/_divisima.html.erb
<div class="divisima">
	<!-- Header section -->

	<!-- Header section end -->

	<% if !main_page %>
		<%= raw header(layout.id) %>
	<%end%>

	<!-- Hero section -->
	<section class="hero-section">
		<div class="hero-slider owl-carousel">
			<div class="hs-item set-bg" data-setbg="/assets/divisima_img/bg.jpg">
				<div class="container">
					<div class="row">
						<div class="col-xl-6 col-lg-7 text-white">
							<span>New Arrivals</span>
							<h2>denim jackets</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus-pendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </p>
							<a href="#" class="site-btn sb-line">DISCOVER</a>
							<a href="#" class="site-btn sb-white">ADD TO CART</a>
						</div>
					</div>
					<div class="offer-card text-white">
						<span>from</span>
						<h2>$29</h2>
						<p>SHOP NOW</p>
					</div>
				</div>
			</div>
			<div class="hs-item set-bg" data-setbg="/assets/divisima_img/bg-2.jpg">
				<div class="container">
					<div class="row">
						<div class="col-xl-6 col-lg-7 text-white">
							<span>New Arrivals</span>
							<h2>denim jackets</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus-pendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </p>
							<a href="#" class="site-btn sb-line">DISCOVER</a>
							<a href="#" class="site-btn sb-white">ADD TO CART</a>
						</div>
					</div>
					<div class="offer-card text-white">
						<span>from</span>
						<h2>$29</h2>
						<p>SHOP NOW</p>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="slide-num-holder" id="snh-1"></div>
		</div>
	</section>
	<!-- Hero section end -->


	<!-- Product filter section -->
	<section class="product-filter-section">
		<div class="container">
			<div class="section-title">
				<h2>BROWSE TOP SELLING PRODUCTS</h2>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/5.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Flamboyant Pink Top </p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<div class="tag-sale">ON SALE</div>
							<img src="/assets/divisima_img/product/6.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Black and White Stripes Dress</p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/7.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Flamboyant Pink Top </p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/8.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Flamboyant Pink Top </p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/9.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Flamboyant Pink Top </p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/10.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Black and White Stripes Dress</p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/11.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Flamboyant Pink Top </p>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<img src="/assets/divisima_img/product/12.jpg" alt="">
						</div>
						<div class="pi-text">
							<h6>$35,00</h6>
							<p>Flamboyant Pink Top </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Product filter section end -->


	<script src="/assets/divisima/js/jquery.slicknav.min.js"></script>
	<script src="/assets/divisima/js/jquery.nicescroll.min.js"></script>
	<script src="/assets/divisima/js/main.js"></script>
</div>

app/views/home/_widget.html.erb
<div class="widget">
    <link rel="stylesheet" href="/assets/widget/css/animate.css">
    <link rel="stylesheet" href="/assets/widget/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/assets/widget/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/assets/widget/css/style.css">
    
    <% if !main_page %>
        <%= raw header(layout.id) %>
    <%end%>

    <section id="home-section" class="hero">
		  <div class="home-slider owl-carousel">
	      <div class="slider-item" style="background-image: url('/assets/widget_img/bg_1.jpg');">
	      	<div class="overlay"></div>
	        <div class="container">
	          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

	            <div class="col-md-12 ftco-animate text-center">
	              <h1 class="mb-2">We serve Fresh Vegestables &amp; Fruits</h1>
	              <h2 class="subheading mb-4">We deliver organic vegetables &amp; fruits</h2>
	              <p><a href="#" class="btn btn-primary">View Details</a></p>
	            </div>

	          </div>
	        </div>
	      </div>

	      <div class="slider-item" style="background-image: url('/assets/widget_img/bg_2.jpg');">
	      	<div class="overlay"></div>
	        <div class="container">
	          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

	            <div class="col-sm-12 ftco-animate text-center">
	              <h1 class="mb-2">100% Fresh &amp; Organic Foods</h1>
	              <h2 class="subheading mb-4">We deliver organic vegetables &amp; fruits</h2>
	              <p><a href="#" class="btn btn-primary">View Details</a></p>
	            </div>

	          </div>
	        </div>
	      </div>
	    </div>
    </section>

    <section class="ftco-section">
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<span class="subheading">Featured Products</span>
            <h2 class="mb-4">Our Products</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
          </div>
        </div>   		
    	</div>
    	<div class="container">
    		<div class="row">
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-1.jpg" alt="Colorlib Template">
                            <div class="overlay"></div>
                        </a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Bell Pepper</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span class="mr-2 price-dc">$120.00</span><span class="price-sale">$80.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-2.jpg" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Strawberry</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>$120.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-3.jpg" alt="Colorlib Template">
	    					<div class="overlay"></div>
	    				</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Green Beans</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>$120.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-4.jpg" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Purple Cabbage</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>$120.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>


    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-5.jpg" alt="Colorlib Template">
    						<span class="status">30%</span>
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Tomatoe</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span class="mr-2 price-dc">$120.00</span><span class="price-sale">$80.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-6.jpg" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Brocolli</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>$120.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-7.jpg" alt="Colorlib Template">
	    					<div class="overlay"></div>
	    				</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Carrots</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>$120.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="/assets/widget_img/product-8.jpg" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">Fruit Juice</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>$120.00</span></p>
		    					</div>
	    					</div>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    </section>

  <script src="/assets/widget/js/jquery.waypoints.min.js"></script>
  <script src="/assets/widget/js/scrollax.min.js"></script>
  <script src="/assets/widget/js/main.js"></script>
    
</div>

app/views/home/_winter.html.erb
<div class="winter">
    <% if !main_page %>
        <%= raw header(layout.id) %>
    <%end%>

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <div class="banner_slider">
                        <div class="single_banner_slider">
                            <div class="banner_text">
                                <div class="banner_text_iner">
                                    <h5>Winter Fasion</h5>
                                    <h1>Fashion Collection 2019</h1>
                                    <a href="#" class="btn_1">shop now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->

    <!-- new arrival part here -->
    <section class="new_arrival section_padding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="new_arrival_iner filter-container">
                        <div class="single_arrivel_item weidth_1 mix shoes">
                            <img src="/assets/winter_img/arrivel/arrivel_5.png" alt="#">
                            <div class="hover_text">
                                <p>Canvas</p>
                                <a href="single-product.html"><h3>Lorem Canvas Low-Top Sneaker</h3></a>
                                <h5>$150</h5>
                            </div>
                        </div>
                        <div class="single_arrivel_item weidth_2 mix women">
                            <img src="/assets/winter_img/arrivel/arrivel_2.png" alt="#">
                            <div class="hover_text">
                                <p>Canvas</p>
                                <a href="single-product.html"><h3>Lorem Canvas Low-Top Sneaker</h3></a>
                                <h5>$150</h5>
                            </div>
                        </div>
                        <div class="single_arrivel_item weidth_3 mix shoes women" >
                            <img src="/assets/winter_img/arrivel/arrivel_3.png" alt="#">
                            <div class="hover_text">
                                <p>Canvas</p>
                                <a href="single-product.html"><h3>Lorem Canvas Low-Top Sneaker</h3></a>
                                <h5>$150</h5>
                            </div>
                        </div>
                        <div class="single_arrivel_item weidth_3 mix women men">
                            <img src="/assets/winter_img/arrivel/arrivel_4.png" alt="#">
                            <div class="hover_text">
                                <p>Canvas</p>
                                <a href="single-product.html"><h3>Lorem Canvas Low-Top Sneaker</h3></a>
                                <h5>$150</h5>
                            </div>
                        </div>
                        <div class="single_arrivel_item weidth_2 mix men women">
                            <img src="/assets/winter_img/arrivel/arrivel_1.png" alt="#">
                            <div class="hover_text">
                                <p>Canvas</p>
                                <a href="single-product.html"><h3>Lorem Canvas Low-Top Sneaker</h3></a>
                                <h5>$150</h5>
                            </div>
                        </div>
                        <div class="single_arrivel_item weidth_1 mix shoes men">
                            <img src="/assets/winter_img/arrivel/arrivel_6.png" alt="#">
                            <div class="hover_text">
                                <p>Canvas</p>
                                <a href="single-product.html"><h3>Lorem Canvas Low-Top Sneaker</h3></a>
                                <h5>$150</h5>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </section>
    <!-- new arrival part end -->
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Ecommerce CMS</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/">Shop</a>
         </li>
         <li class="nav-item active">
         <a href="/default_site" class="btn btn-primary margin-button">Set as default site</a>
         </li>
    </ul>
  </div>
</nav>
<div class="row">
    <div class="container">
        <h1>Themes</h1>
            <div class="row">
                <% @themes.each do |theme| %>
                    <div class="col-4">
                        <div class="card card-body">
                            <%= link_to cm_path(theme) do %>
                                <%= image_tag theme.name + ".png" %>
                            <% end %>
                        </div>
                    </div>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/home/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Ecommerce CMS</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/cms">CMS</a>
         </li>
         <li class="nav-item active">
            <a class="nav-link" href="/">Shop</a>
         </li>
    </ul>
  </div>
</nav>
<div>
    <div class="page-header">
        <a href="<%= cm_widget_path(@theme) %>" class="btn btn-primary margin-button">Create widget</a>
    </div>
    <%= render partial: @theme['name'], locals: { layout: @theme, main_page: false } %>
</div>

app/views/sample/index.html.erb
<div class="mediumcontainer">
</div>

<div class="smallcontainer">

</div>

<div class="largecontainer">
</div>

app/views/spree/checkout/_address.html.erb
<div class="row">
  <div class="col-sm-6" data-hook="billing_fieldset_wrapper">
    <div class="panel panel-default" id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
        </div>
        <div class="panel-body">
          <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-sm-6" data-hook="shipping_fieldset_wrapper">
    <div class="panel panel-default" id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
        </div>
        <div class="panel-body">
          <p class="field checkbox" data-hook="use_billing">
            <%= label_tag :order_use_billing, id: 'use_billing' do %>
              <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
              <%= Spree.t(:use_billing_address) %>
            <% end %>
          </p>
          <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address" class='save-user-address-wrapper'>
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span>
  <% end %>
</div>